repos:
- repo: local
  hooks:
    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [python]
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
    - id: bandit
      name: bandit
      entry: bandit
      language: system
      types: [python]
